### ISSUE TITLE
Link doesn't work

### ISSUE THREAD

**Issue by roykoand** [rust-lang-ua/rustbook_ukrainian#140]
Привіт.
Чудова ініціатива. Випадково помітив, що не працює посилання в рідмі:
https://github.com/rust-lang-ua/rustbook_ukrainian/blob/62b05edf05834f4d0d19b050d00bdf4b9d6afde3/README.md?plain=1#L10
Видає 404 помилку:
https://github.com/rust-lang-ua/rustbook_ukrainian/blob/62b05edf05834f4d0d19b050d00bdf4b9d6afde3/README.md?plain=1#L13

**Comment by MarkTanashchuk** [comment]
Вітаю! Дякую, що підмітили!

Як ви бачите, наш переклад ще не готовий, і саме перекладу ми зараз приділяємо більшість нашої уваги і часу.

Багато з того, що ви бачите ймовірно буде повністю перероблено, тому для того, щоб робота не виконувалася по кілька разів, ми відкладаємо завдання налаштування Github на потім, коли переклад буде готовий.

Якщо вас цікавлять новини про переклад, то можете підписатися на телеграм канал [Вивчаємо Rust Разом 🇺🇦](https://t.me/rustlang_ua). Саме у ньому присутні всі з перекладачів та там в першу чергу будуть опубліковані новини про готовий до використання переклад.

Поки закриваю Issue
