### ISSUE TITLE
Книга не перекладається

### ISSUE THREAD

**Issue by ketronix-dev** [rust-lang-ua/rustbook_ukrainian#161]
А це нормально шо в мене після білду книга на англ мові? Я зробив усе по інструкції як було показано у рідмі, але книга на англ мові.
![image](https://user-images.githubusercontent.com/111521698/196182545-d56a84e4-7e9d-469c-b2a4-6ff18e41fd47.png)

**Comment by ketronix-dev** [comment]
Причому я відкриваю будьякий розділ і там отак

**Comment by pavloslav** [comment]
Наразі так, переклади на Crowdin мають бути затверджені адміністраторами (чи спеціально признач). Загалом, поки хоча б чернетку перекладу не завершимо, це не критично. Тобто ситуація зараз така:
![image](https://user-images.githubusercontent.com/7555805/196463671-eeded74f-155a-49f8-bee1-74c4831f0c9a.png)

**Comment by pavloslav** [comment]
Пофікшено @ChapliaS місяць тому, закриваю issue
