### ISSUE TITLE
Не переведена частина тексту в розділі "2. Програмування гри - відгадайки"

### ISSUE THREAD

**Issue by David-Valters** [rust-lang-ua/rustbook_ukrainian#166]
Книга зібрана, хеш коміту: ba93dc50e1e53965729b86a501a90419c1098d5e
![зображення](https://user-images.githubusercontent.com/46930139/209472495-62267ce8-78ff-4171-b00b-95ef9eb97f08.png)

**Comment by ChapliaS** [comment]
Дякуєм, поправимо!)

**Comment by David-Valters** [comment]
> Дякуєм, поправимо!)

Я також найшов ще декілька не значних, але не приємних косяків, куди я можу відправити інформацію про них ?

**Comment by pavloslav** [comment]
Сюди, будь ласка.
Власне, цей переклад є черновим (хоча ним уже можна користуватися); в планах після завершення перекладу - вичитування.
